service:
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    containerPort: 3000


  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "lets-encrypt"
    hosts:
      - host: helloworld.cloudesence.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          helloworld.cloudesence.com
        secretName: helloworld-tls


# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 5
#   # targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80

image:
  repository: docker.io/caleb2023/helloworld/helloworld
  pullPolicy: IfNotPresent
  tag: latest
